# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poimodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
