# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20180119_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poimodel',
            old_name='descriptions',
            new_name='description',
        ),
    ]
