# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('maps', '0002_auto_20180119_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poimodel',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
    ]
