# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180130_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
    ]
