# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20180201_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='activity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
    ]
