# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 16:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('tag', tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view='tag_autocomplete', blank=True, force_lowercase=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.TagModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('length', models.FloatField(default=0)),
                ('altitude_gain', models.FloatField(default=0)),
                ('altitude_loss', models.FloatField(default=0)),
                ('altitude_max', models.FloatField(default=0)),
                ('altitude_min', models.FloatField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_RouteModel_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tagulous_TrackModel_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('length', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('speed_max', models.FloatField(default=0)),
                ('altitude_gain', models.FloatField(default=0)),
                ('altitude_loss', models.FloatField(default=0)),
                ('altitude_max', models.FloatField(default=0)),
                ('altitude_min', models.FloatField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(dim=3, srid=4326)),
                ('tag', tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view='poi_tag_autocomplete', blank=True, force_lowercase=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Tagulous_TrackModel_tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_trackmodel_tag',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_routemodel_tag',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='tag',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view='poi_tag_autocomplete', blank=True, force_lowercase=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Tagulous_RouteModel_tag'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
