# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 13:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagulous_RouteModel_tag',
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='tag',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view='tag_autocomplete', blank=True, force_lowercase=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.TagModel'),
        ),
    ]
