# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poimodel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel'),
        ),
    ]
