# Generated by Django 2.0.7 on 2018-08-05 13:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('map', '0002_poimodel_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poimodel',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='routemodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
