# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180324_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poimodel',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
