# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='article',
        ),
        migrations.RemoveField(
            model_name='story',
            name='event',
        ),
        migrations.RemoveField(
            model_name='story',
            name='track',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='story',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
