# Generated by Django 2.1.3 on 2018-12-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='locations',
            new_name='location',
        ),
    ]
