# Generated by Django 2.1.3 on 2018-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20181220_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(default='media/avatars/default/default.png', upload_to='media/avatars/'),
        ),
    ]
