# Generated by Django 2.1.4 on 2018-12-27 15:16

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20181223_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(default='avatars/default/default.png', upload_to=profile.models.avatar_user_path),
        ),
    ]
