# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_year.Event'),
        ),
    ]
