# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 12:44
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('story', '0002_auto_20180324_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='tag_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', to='tag.TagModel'),
        ),
    ]
