# Generated by Django 2.0 on 2018-10-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20180805_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storymodel',
            name='article',
        ),
        migrations.AddField(
            model_name='storymodel',
            name='text',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storymodel',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
    ]
