# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0001_initial'),
        ('calendar_year', '0004_auto_20180130_1900'),
        ('maps', '0003_auto_20180130_1900'),
        ('story', '0003_auto_20180114_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleModel',
        ),
        migrations.RemoveField(
            model_name='story',
            name='article',
        ),
        migrations.RemoveField(
            model_name='story',
            name='event',
        ),
        migrations.RemoveField(
            model_name='story',
            name='track',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='story',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='storymodel',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='story.ArticleModel'),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_year.EventModel'),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='tags',
            field=models.ManyToManyField(to='hashtag.TagModel'),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.TrackModel'),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
