# Generated by Django 2.0 on 2018-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20181012_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
