# Generated by Django 2.1.4 on 2019-01-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_storymodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_year.EventModel'),
        ),
    ]
