# Generated by Django 2.1.5 on 2019-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20190107_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='text',
            field=models.TextField(max_length=500000),
        ),
    ]
