# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_year', '0002_event_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='public',
            new_name='is_active',
        ),
    ]
