# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_year', '0003_auto_20180118_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
    ]
