# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_year', '0003_auto_20180227_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
