# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
