# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20180227_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='altitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='altitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='speed_max',
            field=models.FloatField(default=0),
        ),
    ]
