# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 07:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0001_initial'),
        ('track', '0003_auto_20180302_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('length', models.FloatField(default=0)),
                ('altitude_gain', models.FloatField(default=0)),
                ('altitude_loss', models.FloatField(default=0)),
                ('altitude_max', models.FloatField(default=0)),
                ('altitude_min', models.FloatField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtag.TagModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
