# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_routemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodel',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
